### ISSUE TITLE
makeMap.cl gives error Unable to find module 'request' 

### ISSUE THREAD

**Issue by AkshayIyer12** [geekskool/clean#170]
```
[darkJedi@inspiron1545 cleanLang]$ clean makeMap.cl 
module.js:529
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/darkJedi/Work/GeekSkool/cleanLang/makeMap.js:5:17)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
child_process.js:634
    throw err;
    ^

Error: Command failed: node makeMap.js
    at checkExecSyncError (child_process.js:591:13)
    at Object.execSync (child_process.js:631:13)
    at evalFunction (/home/darkJedi/.npm-global/lib/node_modules/cleanlang/lib/cli.js:78:18)
    at module.exports.argsObj (/home/darkJedi/.npm-global/lib/node_modules/cleanlang/lib/cli.js:154:15)
    at Object.<anonymous> (/home/darkJedi/.npm-global/lib/node_modules/cleanlang/lib/clean.js:4:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)```

**Comment by iAmMrinal0** [comment]
You don't have the `request` module installed. Install and try, it should work.

**Comment by AkshayIyer12** [comment]
Ok thanks

**Comment by AkshayIyer12** [comment]
@iAmMrinal0 But even after doing npm install -g request.
It shows the same error `request` module not found.

**Comment by iAmMrinal0** [comment]
Try installing locally.

**Comment by AkshayIyer12** [comment]
Ok Thanks! It works I had to install locally.
